version: "3"
services:
  tasks-md:
      hostname: tasks-md
      container_name: tasks-md
      image: baldissaramatheus/tasks.md
      environment:
        - PUID=1000 #optional
        - PGID=1000 #optional
        - TITLE="My tasks board" #optional
      volumes:
          - api-data:/api/files
          - stylesheets-data:/usr/share/nginx/html/stylesheets/
      restart: unless-stopped
      ports:
        - 8080:8080
volumes:
  api-data:
    driver: local
  stylesheets-data:
    driver: local
